---
- hosts: all
  tasks:
    - name: 'Instala pacotes'
      apt:
        name: 
          - php
          - apache2
          - libapache2-mod-php
          - libssh-4
          - mysql-server
          - python-mysqldb
          - php-mysql
        state: latest
      become: yes